<template><div><h1 id="二维数组转置" tabindex="-1"><a class="header-anchor" href="#二维数组转置"><span>二维数组转置</span></a></h1>
<div class="language-c line-numbers-mode" data-highlighter="prismjs" data-ext="c"><pre v-pre><code><span class="line"> <span class="token number">1</span> #include<span class="token operator">&lt;</span>stdio<span class="token punctuation">.</span>h<span class="token operator">></span> </span>
<span class="line"> <span class="token number">2</span> #include<span class="token operator">&lt;</span>math<span class="token punctuation">.</span>h<span class="token operator">></span></span>
<span class="line"> <span class="token number">3</span> </span>
<span class="line"> <span class="token number">4</span> <span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"> <span class="token number">5</span>     <span class="token comment">//二行三列矩阵，第一行数据为1,2,3；第二行数据为4,5,6 </span></span>
<span class="line"> <span class="token number">6</span>     <span class="token keyword">int</span> arr<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">3</span><span class="token punctuation">}</span><span class="token punctuation">,</span><span class="token punctuation">{</span><span class="token number">4</span><span class="token punctuation">,</span><span class="token number">5</span><span class="token punctuation">,</span><span class="token number">6</span><span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"> <span class="token number">7</span>     <span class="token keyword">int</span> arrTran<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//转置后的矩阵为 3*2</span></span>
<span class="line"> <span class="token number">8</span>     <span class="token keyword">int</span> i<span class="token punctuation">,</span>j<span class="token punctuation">;</span></span>
<span class="line"> <span class="token number">9</span>     </span>
<span class="line"><span class="token number">10</span>     <span class="token comment">//按行输出arr </span></span>
<span class="line"><span class="token number">11</span>     <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"arr is :\n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">12</span>     <span class="token keyword">for</span><span class="token punctuation">(</span>i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> <span class="token number">2</span><span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"><span class="token number">13</span>         <span class="token keyword">for</span><span class="token punctuation">(</span>j <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> j <span class="token operator">&lt;</span> <span class="token number">3</span><span class="token punctuation">;</span> j<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"><span class="token number">14</span>             <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"    %d"</span><span class="token punctuation">,</span> arr<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">15</span>         <span class="token punctuation">}</span></span>
<span class="line"><span class="token number">16</span>         <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"\n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">17</span>     <span class="token punctuation">}</span></span>
<span class="line"><span class="token number">18</span>     </span>
<span class="line"><span class="token number">19</span>     <span class="token comment">//转置就是把i、j调换 </span></span>
<span class="line"><span class="token number">20</span>     <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"arrTran is : \n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">21</span>     <span class="token keyword">for</span><span class="token punctuation">(</span>j <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> j <span class="token operator">&lt;</span> <span class="token number">3</span><span class="token punctuation">;</span> j<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"><span class="token number">22</span>         <span class="token keyword">for</span><span class="token punctuation">(</span>i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> <span class="token number">2</span><span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line"><span class="token number">23</span>             arrTran<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> arr<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">24</span>             <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"    %d"</span><span class="token punctuation">,</span> arrTran<span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">25</span>         <span class="token punctuation">}</span></span>
<span class="line"><span class="token number">26</span>         <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"\n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token number">27</span>     <span class="token punctuation">}</span></span>
<span class="line"><span class="token number">28</span> <span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="https://img2020.cnblogs.com/blog/2194212/202103/2194212-20210301154658335-420758081.png" alt="img"></p>
</div></template>


